<?php

use App\City;
use Illuminate\Database\Seeder;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aCities = array(
            array('name' => "Abdul Hakim",'country_code' => 'PAK'),
            array('name' => "Ahmadpur East",'country_code' => 'PAK'),
            array('name' => "Ahmadpur Lumma",'country_code' => 'PAK'),
            array('name' => "Ahmadpur Sial",'country_code' => 'PAK'),
            array('name' => "Ahmedabad",'country_code' => 'PAK'),
            array('name' => "Alipur",'country_code' => 'PAK'),
            array('name' => "Alipur Chatha",'country_code' => 'PAK'),
            array('name' => "Arifwala",'country_code' => 'PAK'),
            array('name' => "Attock",'country_code' => 'PAK'),
            array('name' => "Baddomalhi",'country_code' => 'PAK'),
            array('name' => "Bagh",'country_code' => 'PAK'),
            array('name' => "Bahawalnagar",'country_code' => 'PAK'),
            array('name' => "Bahawalpur",'country_code' => 'PAK'),
            array('name' => "Bai Pheru",'country_code' => 'PAK'),
            array('name' => "Basirpur",'country_code' => 'PAK'),
            array('name' => "Begowala",'country_code' => 'PAK'),
            array('name' => "Bhakkar",'country_code' => 'PAK'),
            array('name' => "Bhalwal",'country_code' => 'PAK'),
            array('name' => "Bhawana",'country_code' => 'PAK'),
            array('name' => "Bhera",'country_code' => 'PAK'),
            array('name' => "Bhopalwala",'country_code' => 'PAK'),
            array('name' => "Burewala",'country_code' => 'PAK'),
            array('name' => "Chak Azam Sahu",'country_code' => 'PAK'),
            array('name' => "Chak Jhumra",'country_code' => 'PAK'),
            array('name' => "Chak Sarwar Shahid",'country_code' => 'PAK'),
            array('name' => "Chakwal",'country_code' => 'PAK'),
            array('name' => "Chawinda",'country_code' => 'PAK'),
            array('name' => "Chichawatni",'country_code' => 'PAK'),
            array('name' => "Chiniot",'country_code' => 'PAK'),
            array('name' => "Chishtian Mandi",'country_code' => 'PAK'),
            array('name' => "Choa Saidan Shah",'country_code' => 'PAK'),
            array('name' => "Chuhar Kana",'country_code' => 'PAK'),
            array('name' => "Chunian",'country_code' => 'PAK'),
            array('name' => "Dajal",'country_code' => 'PAK'),
            array('name' => "Darya Khan",'country_code' => 'PAK'),
            array('name' => "Daska",'country_code' => 'PAK'),
            array('name' => "Daud Khel",'country_code' => 'PAK'),
            array('name' => "Daultala",'country_code' => 'PAK'),
            array('name' => "Dera Din Panah",'country_code' => 'PAK'),
            array('name' => "Dera Ghazi Khan",'country_code' => 'PAK'),
            array('name' => "Dhanote",'country_code' => 'PAK'),
            array('name' => "Dhonkal",'country_code' => 'PAK'),
            array('name' => "Dijkot",'country_code' => 'PAK'),
            array('name' => "Dina",'country_code' => 'PAK'),
            array('name' => "Dinga",'country_code' => 'PAK'),
            array('name' => "Dipalpur",'country_code' => 'PAK'),
            array('name' => "Dullewala",'country_code' => 'PAK'),
            array('name' => "Dunga Bunga",'country_code' => 'PAK'),
            array('name' => "Dunyapur",'country_code' => 'PAK'),
            array('name' => "Eminabad",'country_code' => 'PAK'),
            array('name' => "Faisalabad",'country_code' => 'PAK'),
            array('name' => "Faqirwali",'country_code' => 'PAK'),
            array('name' => "Faruka",'country_code' => 'PAK'),
            array('name' => "Fateh Jang",'country_code' => 'PAK'),
            array('name' => "Fatehpur",'country_code' => 'PAK'),
            array('name' => "Fazalpur",'country_code' => 'PAK'),
            array('name' => "Ferozwala",'country_code' => 'PAK'),
            array('name' => "Fort Abbas",'country_code' => 'PAK'),
            array('name' => "Garh Maharaja",'country_code' => 'PAK'),
            array('name' => "Ghakar",'country_code' => 'PAK'),
            array('name' => "Ghurgushti",'country_code' => 'PAK'),
            array('name' => "Gojra",'country_code' => 'PAK'),
            array('name' => "Gujar Khan",'country_code' => 'PAK'),
            array('name' => "Gujranwala",'country_code' => 'PAK'),
            array('name' => "Gujrat",'country_code' => 'PAK'),
            array('name' => "Hadali",'country_code' => 'PAK'),
            array('name' => "Hafizabad",'country_code' => 'PAK'),
            array('name' => "Harnoli",'country_code' => 'PAK'),
            array('name' => "Harunabad",'country_code' => 'PAK'),
            array('name' => "Hasan Abdal",'country_code' => 'PAK'),
            array('name' => "Hasilpur",'country_code' => 'PAK'),
            array('name' => "Haveli",'country_code' => 'PAK'),
            array('name' => "Hazro",'country_code' => 'PAK'),
            array('name' => "Hujra Shah Muqim",'country_code' => 'PAK'),
            array('name' => "Isa Khel",'country_code' => 'PAK'),
            array('name' => "Islamabad",'country_code' => 'PAK'),
            array('name' => "Jahanian",'country_code' => 'PAK'),
            array('name' => "Jalalpur Bhattian",'country_code' => 'PAK'),
            array('name' => "Jalalpur Jattan",'country_code' => 'PAK'),
            array('name' => "Jalalpur Pirwala",'country_code' => 'PAK'),
            array('name' => "Jalla Jeem",'country_code' => 'PAK'),
            array('name' => "Jamke Chima",'country_code' => 'PAK'),
            array('name' => "Jampur",'country_code' => 'PAK'),
            array('name' => "Jand",'country_code' => 'PAK'),
            array('name' => "Jandanwala",'country_code' => 'PAK'),
            array('name' => "Jandiala Sherkhan",'country_code' => 'PAK'),
            array('name' => "Jaranwala",'country_code' => 'PAK'),
            array('name' => "Jatoi",'country_code' => 'PAK'),
            array('name' => "Jauharabad",'country_code' => 'PAK'),
            array('name' => "Jhang",'country_code' => 'PAK'),
            array('name' => "Jhawarian",'country_code' => 'PAK'),
            array('name' => "Jhelum",'country_code' => 'PAK'),
            array('name' => "Kabirwala",'country_code' => 'PAK'),
            array('name' => "Kahna Nau",'country_code' => 'PAK'),
            array('name' => "Kahror Pakka",'country_code' => 'PAK'),
            array('name' => "Kahuta",'country_code' => 'PAK'),
            array('name' => "Kalabagh",'country_code' => 'PAK'),
            array('name' => "Kalaswala",'country_code' => 'PAK'),
            array('name' => "Kaleke",'country_code' => 'PAK'),
            array('name' => "Kalur Kot",'country_code' => 'PAK'),
            array('name' => "Kamalia",'country_code' => 'PAK'),
            array('name' => "Kamar Mashani",'country_code' => 'PAK'),
            array('name' => "Kamir",'country_code' => 'PAK'),
            array('name' => "Kamoke",'country_code' => 'PAK'),
            array('name' => "Kamra",'country_code' => 'PAK'),
            array('name' => "Kanganpur",'country_code' => 'PAK'),
            array('name' => "Karampur",'country_code' => 'PAK'),
            array('name' => "Karor Lal Esan",'country_code' => 'PAK'),
            array('name' => "Kasur",'country_code' => 'PAK'),
            array('name' => "Khairpur Tamewali",'country_code' => 'PAK'),
            array('name' => "Khanewal",'country_code' => 'PAK'),
            array('name' => "Khangah Dogran",'country_code' => 'PAK'),
            array('name' => "Khangarh",'country_code' => 'PAK'),
            array('name' => "Khanpur",'country_code' => 'PAK'),
            array('name' => "Kharian",'country_code' => 'PAK'),
            array('name' => "Khewra",'country_code' => 'PAK'),
            array('name' => "Khundian",'country_code' => 'PAK'),
            array('name' => "Khurianwala",'country_code' => 'PAK'),
            array('name' => "Khushab",'country_code' => 'PAK'),
            array('name' => "Kot Abdul Malik",'country_code' => 'PAK'),
            array('name' => "Kot Addu",'country_code' => 'PAK'),
            array('name' => "Kot Mithan",'country_code' => 'PAK'),
            array('name' => "Kot Moman",'country_code' => 'PAK'),
            array('name' => "Kot Radha Kishan",'country_code' => 'PAK'),
            array('name' => "Kot Samaba",'country_code' => 'PAK'),
            array('name' => "Kotli Loharan",'country_code' => 'PAK'),
            array('name' => "Kundian",'country_code' => 'PAK'),
            array('name' => "Kunjah",'country_code' => 'PAK'),
            array('name' => "Lahore",'country_code' => 'PAK'),
            array('name' => "Lalamusa",'country_code' => 'PAK'),
            array('name' => "Lalian",'country_code' => 'PAK'),
            array('name' => "Liaqatabad",'country_code' => 'PAK'),
            array('name' => "Liaqatpur",'country_code' => 'PAK'),
            array('name' => "Lieah",'country_code' => 'PAK'),
            array('name' => "Liliani",'country_code' => 'PAK'),
            array('name' => "Lodhran",'country_code' => 'PAK'),
            array('name' => "Ludhewala Waraich",'country_code' => 'PAK'),
            array('name' => "Mailsi",'country_code' => 'PAK'),
            array('name' => "Makhdumpur",'country_code' => 'PAK'),
            array('name' => "Makhdumpur Rashid",'country_code' => 'PAK'),
            array('name' => "Malakwal",'country_code' => 'PAK'),
            array('name' => "Mamu Kanjan",'country_code' => 'PAK'),
            array('name' => "Mananwala Jodh Singh",'country_code' => 'PAK'),
            array('name' => "Mandi Bahauddin",'country_code' => 'PAK'),
            array('name' => "Mandi Sadiq Ganj",'country_code' => 'PAK'),
            array('name' => "Mangat",'country_code' => 'PAK'),
            array('name' => "Mangla",'country_code' => 'PAK'),
            array('name' => "Mankera",'country_code' => 'PAK'),
            array('name' => "Mian Channun",'country_code' => 'PAK'),
            array('name' => "Miani",'country_code' => 'PAK'),
            array('name' => "Mianwali",'country_code' => 'PAK'),
            array('name' => "Minchinabad",'country_code' => 'PAK'),
            array('name' => "Mitha Tiwana",'country_code' => 'PAK'),
            array('name' => "Multan",'country_code' => 'PAK'),
            array('name' => "Muridke",'country_code' => 'PAK'),
            array('name' => "Murree",'country_code' => 'PAK'),
            array('name' => "Mustafabad",'country_code' => 'PAK'),
            array('name' => "Muzaffargarh",'country_code' => 'PAK'),
            array('name' => "Nankana Sahib",'country_code' => 'PAK'),
            array('name' => "Narang",'country_code' => 'PAK'),
            array('name' => "Narowal",'country_code' => 'PAK'),
            array('name' => "Noorpur Thal",'country_code' => 'PAK'),
            array('name' => "Nowshera",'country_code' => 'PAK'),
            array('name' => "Nowshera Virkan",'country_code' => 'PAK'),
            array('name' => "Okara",'country_code' => 'PAK'),
            array('name' => "Pakpattan",'country_code' => 'PAK'),
            array('name' => "Pasrur",'country_code' => 'PAK'),
            array('name' => "Pattoki",'country_code' => 'PAK'),
            array('name' => "Phalia",'country_code' => 'PAK'),
            array('name' => "Phularwan",'country_code' => 'PAK'),
            array('name' => "Pind Dadan Khan",'country_code' => 'PAK'),
            array('name' => "Pindi Bhattian",'country_code' => 'PAK'),
            array('name' => "Pindi Gheb",'country_code' => 'PAK'),
            array('name' => "Pirmahal",'country_code' => 'PAK'),
            array('name' => "Qadirabad",'country_code' => 'PAK'),
            array('name' => "Qadirpur Ran",'country_code' => 'PAK'),
            array('name' => "Qila Disar Singh",'country_code' => 'PAK'),
            array('name' => "Qila Sobha Singh",'country_code' => 'PAK'),
            array('name' => "Quaidabad",'country_code' => 'PAK'),
            array('name' => "Rabwah",'country_code' => 'PAK'),
            array('name' => "Rahim Yar Khan",'country_code' => 'PAK'),
            array('name' => "Raiwind",'country_code' => 'PAK'),
            array('name' => "Raja Jang",'country_code' => 'PAK'),
            array('name' => "Rajanpur",'country_code' => 'PAK'),
            array('name' => "Rasulnagar",'country_code' => 'PAK'),
            array('name' => "Rawalpindi",'country_code' => 'PAK'),
            array('name' => "Renala Khurd",'country_code' => 'PAK'),
            array('name' => "Rojhan",'country_code' => 'PAK'),
            array('name' => "Saddar Gogera",'country_code' => 'PAK'),
            array('name' => "Sadiqabad",'country_code' => 'PAK'),
            array('name' => "Safdarabad",'country_code' => 'PAK'),
            array('name' => "Sahiwal",'country_code' => 'PAK'),
            array('name' => "Samasatta",'country_code' => 'PAK'),
            array('name' => "Sambrial",'country_code' => 'PAK'),
            array('name' => "Sammundri",'country_code' => 'PAK'),
            array('name' => "Sangala Hill",'country_code' => 'PAK'),
            array('name' => "Sanjwal",'country_code' => 'PAK'),
            array('name' => "Sarai Alamgir",'country_code' => 'PAK'),
            array('name' => "Sarai Sidhu",'country_code' => 'PAK'),
            array('name' => "Sargodha",'country_code' => 'PAK'),
            array('name' => "Shadiwal",'country_code' => 'PAK'),
            array('name' => "Shahkot",'country_code' => 'PAK'),
            array('name' => "Shahpur City",'country_code' => 'PAK'),
            array('name' => "Shahpur Saddar",'country_code' => 'PAK'),
            array('name' => "Shakargarh",'country_code' => 'PAK'),
            array('name' => "Sharqpur",'country_code' => 'PAK'),
            array('name' => "Shehr Sultan",'country_code' => 'PAK'),
            array('name' => "Shekhupura",'country_code' => 'PAK'),
            array('name' => "Shujaabad",'country_code' => 'PAK'),
            array('name' => "Sialkot",'country_code' => 'PAK'),
            array('name' => "Sillanwali",'country_code' => 'PAK'),
            array('name' => "Sodhra",'country_code' => 'PAK'),
            array('name' => "Sohawa",'country_code' => 'PAK'),
            array('name' => "Sukheke",'country_code' => 'PAK'),
            array('name' => "Talagang",'country_code' => 'PAK'),
            array('name' => "Tandlianwala",'country_code' => 'PAK'),
            array('name' => "Taunsa",'country_code' => 'PAK'),
            array('name' => "Taxila",'country_code' => 'PAK'),
            array('name' => "Tibba Sultanpur",'country_code' => 'PAK'),
            array('name' => "Toba Tek Singh",'country_code' => 'PAK'),
            array('name' => "Tulamba",'country_code' => 'PAK'),
            array('name' => "Uch",'country_code' => 'PAK'),
            array('name' => "Vihari",'country_code' => 'PAK'),
            array('name' => "Wah",'country_code' => 'PAK'),
            array('name' => "Warburton",'country_code' => 'PAK'),
            array('name' => "Wazirabad",'country_code' => 'PAK'),
            array('name' => "Yazman",'country_code' => 'PAK'),
            array('name' => "Zafarwal",'country_code' => 'PAK'),
            array('name' => "Zahir Pir",'country_code' => 'PAK'),
            array('name' => "Adilpur",'country_code'=>'PAK'),
            array('name' => "Badah",'country_code'=>'PAK'),
            array('name' => "Badin",'country_code'=>'PAK'),
            array('name' => "Bagarji",'country_code'=>'PAK'),
            array('name' => "Bakshshapur",'country_code'=>'PAK'),
            array('name' => "Bandhi",'country_code'=>'PAK'),
            array('name' => "Berani",'country_code'=>'PAK'),
            array('name' => "Bhan",'country_code'=>'PAK'),
            array('name' => "Bhiria City",'country_code'=>'PAK'),
            array('name' => "Bhiria Road",'country_code'=>'PAK'),
            array('name' => "Bhit Shah",'country_code'=>'PAK'),
            array('name' => "Bozdar",'country_code'=>'PAK'),
            array('name' => "Bulri",'country_code'=>'PAK'),
            array('name' => "Chak",'country_code'=>'PAK'),
            array('name' => "Chambar",'country_code'=>'PAK'),
            array('name' => "Chohar Jamali",'country_code'=>'PAK'),
            array('name' => "Chor",'country_code'=>'PAK'),
            array('name' => "Dadu",'country_code'=>'PAK'),
            array('name' => "Daharki",'country_code'=>'PAK'),
            array('name' => "Daro",'country_code'=>'PAK'),
            array('name' => "Darya Khan Mari",'country_code'=>'PAK'),
            array('name' => "Daulatpur",'country_code'=>'PAK'),
            array('name' => "Daur",'country_code'=>'PAK'),
            array('name' => "Dhoronaro",'country_code'=>'PAK'),
            array('name' => "Digri",'country_code'=>'PAK'),
            array('name' => "Diplo",'country_code'=>'PAK'),
            array('name' => "Dokri",'country_code'=>'PAK'),
            array('name' => "Faqirabad",'country_code'=>'PAK'),
            array('name' => "Gambat",'country_code'=>'PAK'),
            array('name' => "Garello",'country_code'=>'PAK'),
            array('name' => "Garhi Khairo",'country_code'=>'PAK'),
            array('name' => "Garhi Yasin",'country_code'=>'PAK'),
            array('name' => "Gharo",'country_code'=>'PAK'),
            array('name' => "Ghauspur",'country_code'=>'PAK'),
            array('name' => "Ghotki",'country_code'=>'PAK'),
            array('name' => "Golarchi",'country_code'=>'PAK'),
            array('name' => "Guddu",'country_code'=>'PAK'),
            array('name' => "Gulistan-E-Jauhar",'country_code'=>'PAK'),
            array('name' => "Hala",'country_code'=>'PAK'),
            array('name' => "Hingorja",'country_code'=>'PAK'),
            array('name' => "Hyderabad",'country_code'=>'PAK'),
            array('name' => "Islamkot",'country_code'=>'PAK'),
            array('name' => "Jacobabad",'country_code'=>'PAK'),
            array('name' => "Jam Nawaz Ali",'country_code'=>'PAK'),
            array('name' => "Jam Sahib",'country_code'=>'PAK'),
            array('name' => "Jati",'country_code'=>'PAK'),
            array('name' => "Jhol",'country_code'=>'PAK'),
            array('name' => "Jhudo",'country_code'=>'PAK'),
            array('name' => "Johi",'country_code'=>'PAK'),
            array('name' => "Kadhan",'country_code'=>'PAK'),
            array('name' => "Kambar",'country_code'=>'PAK'),
            array('name' => "Kandhra",'country_code'=>'PAK'),
            array('name' => "Kandiari",'country_code'=>'PAK'),
            array('name' => "Kandiaro",'country_code'=>'PAK'),
            array('name' => "Karachi",'country_code'=>'PAK'),
            array('name' => "Karampur",'country_code'=>'PAK'),
            array('name' => "Kario Ghanwar",'country_code'=>'PAK'),
            array('name' => "Karoondi",'country_code'=>'PAK'),
            array('name' => "Kashmor",'country_code'=>'PAK'),
            array('name' => "Kazi Ahmad",'country_code'=>'PAK'),
            array('name' => "Keti Bandar",'country_code'=>'PAK'),
            array('name' => "Khadro",'country_code'=>'PAK'),
            array('name' => "Khairpur",'country_code'=>'PAK'),
            array('name' => "Khairpur Nathan Shah",'country_code'=>'PAK'),
            array('name' => "Khandh Kot",'country_code'=>'PAK'),
            array('name' => "Khanpur",'country_code'=>'PAK'),
            array('name' => "Khipro",'country_code'=>'PAK'),
            array('name' => "Khoski",'country_code'=>'PAK'),
            array('name' => "Khuhra",'country_code'=>'PAK'),
            array('name' => "Khyber",'country_code'=>'PAK'),
            array('name' => "Kot Diji",'country_code'=>'PAK'),
            array('name' => "Kot Ghulam Mohammad",'country_code'=>'PAK'),
            array('name' => "Kotri",'country_code'=>'PAK'),
            array('name' => "Kumb",'country_code'=>'PAK'),
            array('name' => "Kunri",'country_code'=>'PAK'),
            array('name' => "Lakhi",'country_code'=>'PAK'),
            array('name' => "Larkana",'country_code'=>'PAK'),
            array('name' => "Madeji",'country_code'=>'PAK'),
            array('name' => "Matiari",'country_code'=>'PAK'),
            array('name' => "Matli",'country_code'=>'PAK'),
            array('name' => "Mehar",'country_code'=>'PAK'),
            array('name' => "Mehrabpur",'country_code'=>'PAK'),
            array('name' => "Miro Khan",'country_code'=>'PAK'),
            array('name' => "Mirpur Bathoro",'country_code'=>'PAK'),
            array('name' => "Mirpur Khas",'country_code'=>'PAK'),
            array('name' => "Mirpur Mathelo",'country_code'=>'PAK'),
            array('name' => "Mirpur Sakro",'country_code'=>'PAK'),
            array('name' => "Mirwah",'country_code'=>'PAK'),
            array('name' => "Mithi",'country_code'=>'PAK'),
            array('name' => "Moro",'country_code'=>'PAK'),
            array('name' => "Nabisar",'country_code'=>'PAK'),
            array('name' => "Nasarpur",'country_code'=>'PAK'),
            array('name' => "Nasirabad",'country_code'=>'PAK'),
            array('name' => "Naudero",'country_code'=>'PAK'),
            array('name' => "Naukot",'country_code'=>'PAK'),
            array('name' => "Naushahro Firoz",'country_code'=>'PAK'),
            array('name' => "Nawabshah",'country_code'=>'PAK'),
            array('name' => "Oderolal Station",'country_code'=>'PAK'),
            array('name' => "Pacca Chang",'country_code'=>'PAK'),
            array('name' => "Padidan",'country_code'=>'PAK'),
            array('name' => "Pano Aqil",'country_code'=>'PAK'),
            array('name' => "Perumal",'country_code'=>'PAK'),
            array('name' => "Phulji",'country_code'=>'PAK'),
            array('name' => "Pirjo Goth",'country_code'=>'PAK'),
            array('name' => "Piryaloi",'country_code'=>'PAK'),
            array('name' => "Pithoro",'country_code'=>'PAK'),
            array('name' => "Radhan",'country_code'=>'PAK'),
            array('name' => "Rajo Khanani",'country_code'=>'PAK'),
            array('name' => "Ranipur",'country_code'=>'PAK'),
            array('name' => "Ratodero",'country_code'=>'PAK'),
            array('name' => "Rohri",'country_code'=>'PAK'),
            array('name' => "Rustam",'country_code'=>'PAK'),
            array('name' => "Saeedabad",'country_code'=>'PAK'),
            array('name' => "Sakrand",'country_code'=>'PAK'),
            array('name' => "Samaro",'country_code'=>'PAK'),
            array('name' => "Sanghar",'country_code'=>'PAK'),
            array('name' => "Sann",'country_code'=>'PAK'),
            array('name' => "Sarhari",'country_code'=>'PAK'),
            array('name' => "Sehwan",'country_code'=>'PAK'),
            array('name' => "Setharja",'country_code'=>'PAK'),
            array('name' => "Shah Dipalli",'country_code'=>'PAK'),
            array('name' => "Shahdadkot",'country_code'=>'PAK'),
            array('name' => "Shahdadpur",'country_code'=>'PAK'),
            array('name' => "Shahpur Chakar",'country_code'=>'PAK'),
            array('name' => "Shahpur Jahania",'country_code'=>'PAK'),
            array('name' => "Shikarpur",'country_code'=>'PAK'),
            array('name' => "Sinjhoro",'country_code'=>'PAK'),
            array('name' => "Sita Road",'country_code'=>'PAK'),
            array('name' => "Sobhodero",'country_code'=>'PAK'),
            array('name' => "Sujawal",'country_code'=>'PAK'),
            array('name' => "Sukkur",'country_code'=>'PAK'),
            array('name' => "Talhar",'country_code'=>'PAK'),
            array('name' => "Tando Adam",'country_code'=>'PAK'),
            array('name' => "Tando Allah Yar",'country_code'=>'PAK'),
            array('name' => "Tando Bagho",'country_code'=>'PAK'),
            array('name' => "Tando Ghulam Ali",'country_code'=>'PAK'),
            array('name' => "Tando Jam",'country_code'=>'PAK'),
            array('name' => "Tando Jan Mohammad",'country_code'=>'PAK'),
            array('name' => "Tando Mitha Khan",'country_code'=>'PAK'),
            array('name' => "Tando Muhammad Khan",'country_code'=>'PAK'),
            array('name' => "Tangwani",'country_code'=>'PAK'),
            array('name' => "Thano Bula Khan",'country_code'=>'PAK'),
            array('name' => "Thari Mirwah",'country_code'=>'PAK'),
            array('name' => "Tharushah",'country_code'=>'PAK'),
            array('name' => "Thatta",'country_code'=>'PAK'),
            array('name' => "Ther I",'country_code'=>'PAK'),
            array('name' => "Ther I Mohabat",'country_code'=>'PAK'),
            array('name' => "Thul",'country_code'=>'PAK'),
            array('name' => "Ubauro",'country_code'=>'PAK'),
            array('name' => "Umarkot",'country_code'=>'PAK'),
            array('name' => "Athmuqam",'country_code'=>'PAK'),
            array('name' => "Bagh",'country_code'=>'PAK'),
            array('name' => "Bhimber",'country_code'=>'PAK'),
            array('name' => "Hattian",'country_code'=>'PAK'),
            array('name' => "Haveli",'country_code'=>'PAK'),
            array('name' => "Khuiratta",'country_code'=>'PAK'),
            array('name' => "Kotli",'country_code'=>'PAK'),
            array('name' => "Mangla",'country_code'=>'PAK'),
            array('name' => "Mirpur",'country_code'=>'PAK'),
            array('name' => "Muzaffarabad",'country_code'=>'PAK'),
            array('name' => "Neelam",'country_code'=>'PAK'),
            array('name' => "Palandri",'country_code'=>'PAK'),
            array('name' => "Poonch",'country_code'=>'PAK'),
            array('name' => "Rawalakot",'country_code'=>'PAK'),
            array('name' => "Sudhnoti",'country_code'=>'PAK'),

            array('name' => "Amir chah",'country_code'=>'PAK'),
            array('name' => "Awaran",'country_code'=>'PAK'),
            array('name' => "Barkhan",'country_code'=>'PAK'),
            array('name' => "Bela",'country_code'=>'PAK'),
            array('name' => "Bhag",'country_code'=>'PAK'),
            array('name' => "Chaman",'country_code'=>'PAK'),
            array('name' => "Chitkan",'country_code'=>'PAK'),
            array('name' => "Dalbandin",'country_code'=>'PAK'),
            array('name' => "Dera Allah Yar",'country_code'=>'PAK'),
            array('name' => "Dera Bugti",'country_code'=>'PAK'),
            array('name' => "Dera Murad Jamali",'country_code'=>'PAK'),
            array('name' => "Dhadar",'country_code'=>'PAK'),
            array('name' => "Duki",'country_code'=>'PAK'),
            array('name' => "Gaddani",'country_code'=>'PAK'),
            array('name' => "Gwadar",'country_code'=>'PAK'),
            array('name' => "Harnai",'country_code'=>'PAK'),
            array('name' => "Hub",'country_code'=>'PAK'),
            array('name' => "Jiwani",'country_code'=>'PAK'),
            array('name' => "Kalat",'country_code'=>'PAK'),
            array('name' => "Kharan",'country_code'=>'PAK'),
            array('name' => "Khuzdar",'country_code'=>'PAK'),
            array('name' => "Kohlu",'country_code'=>'PAK'),
            array('name' => "Loralai",'country_code'=>'PAK'),
            array('name' => "Mach",'country_code'=>'PAK'),
            array('name' => "Mastung",'country_code'=>'PAK'),
            array('name' => "Nushki",'country_code'=>'PAK'),
            array('name' => "Ormara",'country_code'=>'PAK'),
            array('name' => "Pasni",'country_code'=>'PAK'),
            array('name' => "Pishin",'country_code'=>'PAK'),
            array('name' => "Quetta",'country_code'=>'PAK'),
            array('name' => "Sibi",'country_code'=>'PAK'),
            array('name' => "Sohbatpur",'country_code'=>'PAK'),
            array('name' => "Surab",'country_code'=>'PAK'),
            array('name' => "Turbat",'country_code'=>'PAK'),
            array('name' => "Usta Muhammad",'country_code'=>'PAK'),
            array('name' => "Uthal",'country_code'=>'PAK'),
            array('name' => "Wadh",'country_code'=>'PAK'),
            array('name' => "Winder",'country_code'=>'PAK'),
            array('name' => "Zehri",'country_code'=>'PAK'),
            array('name' => "Zhob",'country_code'=>'PAK'),
            array('name' => "Ziarat",'country_code'=>'PAK'),
        );
        foreach ($aCities as $city) {
            City::create($city);
          }
    }
}
