<?php
use App\Country;
use Carbon\Carbon;
use Faker\Factory;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aCountries = array(
            array('id' => '1',             'name' => 'Afghanistan','code' => 'AFG','numcode' => '4','phonecode' => '93'),
            array('id' => '2',             'name' => 'Albania','code' => 'ALB','numcode' => '8','phonecode' => '355'),
            array('id' => '3',             'name' => 'Algeria','code' => 'DZA','numcode' => '12','phonecode' => '213'),
            array('id' => '4',         'name' => 'American Samoa','code' => 'ASM','numcode' => '16','phonecode' => '1684'),
            array('id' => '5',             'name' => 'Andorra','code' => 'AND','numcode' => '20','phonecode' => '376'),
            array('id' => '6',         'name' => 'Angola','code' => 'AGO','numcode' => '24','phonecode' => '244'),
            array('id' => '7',             'name' => 'Anguilla','code' => 'AIA','numcode' => '660','phonecode' => '1264'),
            array('id' => '8',         'name' => 'Antarctica','code' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '9',             'name' => 'Antigua and Barbuda','code' => 'ATG','numcode' => '28','phonecode' => '1268'),
            array('id' => '10',        'name' => 'Argentina','code' => 'ARG','numcode' => '32','phonecode' => '54'),
            array('id' => '11',            'name' => 'Armenia','code' => 'ARM','numcode' => '51','phonecode' => '374'),
            array('id' => '12',        'name' => 'Aruba','code' => 'ABW','numcode' => '533','phonecode' => '297'),
            array('id' => '13',        'name' => 'Australia','code' => 'AUS','numcode' => '36','phonecode' => '61'),
            array('id' => '14',            'name' => 'Austria','code' => 'AUT','numcode' => '40','phonecode' => '43'),
            array('id' => '15',        'name' => 'Azerbaijan','code' => 'AZE','numcode' => '31','phonecode' => '994'),
            array('id' => '16',            'name' => 'Bahamas','code' => 'BHS','numcode' => '44','phonecode' => '1242'),
            array('id' => '17',            'name' => 'Bahrain','code' => 'BHR','numcode' => '48','phonecode' => '973'),
            array('id' => '18',        'name' => 'Bangladesh','code' => 'BGD','numcode' => '50','phonecode' => '880'),
            array('id' => '19',            'name' => 'Barbados','code' => 'BRB','numcode' => '52','phonecode' => '1246'),
            array('id' => '20',            'name' => 'Belarus','code' => 'BLR','numcode' => '112','phonecode' => '375'),
            array('id' => '21',            'name' => 'Belgium','code' => 'BEL','numcode' => '56','phonecode' => '32'),
            array('id' => '22',        'name' => 'Belize','code' => 'BLZ','numcode' => '84','phonecode' => '501'),
            array('id' => '23',        'name' => 'Benin','code' => 'BEN','numcode' => '204','phonecode' => '229'),
            array('id' => '24',            'name' => 'Bermuda','code' => 'BMU','numcode' => '60','phonecode' => '1441'),
            array('id' => '25',        'name' => 'Bhutan','code' => 'BTN','numcode' => '64','phonecode' => '975'),
            array('id' => '26',            'name' => 'Bolivia','code' => 'BOL','numcode' => '68','phonecode' => '591'),
            array('id' => '27',    'name' => 'Bosnia and Herzegovina','code' => 'BIH','numcode' => '70','phonecode' => '387'),
            array('id' => '28',            'name' => 'Botswana','code' => 'BWA','numcode' => '72','phonecode' => '267'),
            array('id' => '29',        'name' => 'Bouvet Island','code' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '30',        'name' => 'Brazil','code' => 'BRA','numcode' => '76','phonecode' => '55'),
            array('id' => '31',        'name' => 'British Indian Ocean Territory','code' => NULL,'numcode' => NULL,'phonecode' => '246'),
            array('id' => '32',        'name' => 'Brunei Darussalam','code' => 'BRN','numcode' => '96','phonecode' => '673'),
            array('id' => '33',            'name' => 'Bulgaria','code' => 'BGR','numcode' => '100','phonecode' => '359'),
            array('id' => '34',        'name' => 'Burkina Faso','code' => 'BFA','numcode' => '854','phonecode' => '226'),
            array('id' => '35',            'name' => 'Burundi','code' => 'BDI','numcode' => '108','phonecode' => '257'),
            array('id' => '36',            'name' => 'Cambodia','code' => 'KHM','numcode' => '116','phonecode' => '855'),
            array('id' => '37',            'name' => 'Cameroon','code' => 'CMR','numcode' => '120','phonecode' => '237'),
            array('id' => '38',        'name' => 'Canada','code' => 'CAN','numcode' => '124','phonecode' => '1'),
            array('id' => '39',    'name' => 'Cape Verde','code' => 'CPV','numcode' => '132','phonecode' => '238'),
            array('id' => '40',    'name' => 'Cayman Islands','code' => 'CYM','numcode' => '136','phonecode' => '1345'),
            array('id' => '41',        'name' => 'Central African Republic','code' => 'CAF','numcode' => '140','phonecode' => '236'),
            array('id' => '42',            'name' => 'Chad','code' => 'TCD','numcode' => '148','phonecode' => '235'),
            array('id' => '43',        'name' => 'Chile','code' => 'CHL','numcode' => '152','phonecode' => '56'),
            array('id' => '44',        'name' => 'China','code' => 'CHN','numcode' => '156','phonecode' => '86'),
            array('id' => '45',        'name' => 'Christmas Island','code' => NULL,'numcode' => NULL,'phonecode' => '61'),
            array('id' => '46',        'name' => 'Cocos (Keeling) Islands','code' => NULL,'numcode' => NULL,'phonecode' => '672'),
            array('id' => '47',            'name' => 'Colombia','code' => 'COL','numcode' => '170','phonecode' => '57'),
            array('id' => '48',            'name' => 'Comoros','code' => 'COM','numcode' => '174','phonecode' => '269'),
            array('id' => '49',        'name' => 'Congo','code' => 'COG','numcode' => '178','phonecode' => '242'),
            array('id' => '50',        'name' => 'Congo, the Democratic Republic of the','code' => 'COD','numcode' => '180','phonecode' => '242'),
            array('id' => '51',        'name' => 'Cook Islands','code' => 'COK','numcode' => '184','phonecode' => '682'),
            array('id' => '52',    'name' => 'Costa Rica','code' => 'CRI','numcode' => '188','phonecode' => '506'),
            array('id' => '53',    'name' => 'Cote D\'Ivoire','code' => 'CIV','numcode' => '384','phonecode' => '225'),
            array('id' => '54',            'name' => 'Croatia','code' => 'HRV','numcode' => '191','phonecode' => '385'),
            array('id' => '55',            'name' => 'Cuba','code' => 'CUB','numcode' => '192','phonecode' => '53'),
            array('id' => '56',        'name' => 'Cyprus','code' => 'CYP','numcode' => '196','phonecode' => '357'),
            array('id' => '57',    'name' => 'Czech Republic','code' => 'CZE','numcode' => '203','phonecode' => '420'),
            array('id' => '58',            'name' => 'Denmark','code' => 'DNK','numcode' => '208','phonecode' => '45'),
            array('id' => '59',            'name' => 'Djibouti','code' => 'DJI','numcode' => '262','phonecode' => '253'),
            array('id' => '60',            'name' => 'Dominica','code' => 'DMA','numcode' => '212','phonecode' => '1767'),
            array('id' => '61',    'name' => 'Dominican Republic','code' => 'DOM','numcode' => '214','phonecode' => '1809'),
            array('id' => '62',            'name' => 'Ecuador','code' => 'ECU','numcode' => '218','phonecode' => '593'),
            array('id' => '63',        'name' => 'Egypt','code' => 'EGY','numcode' => '818','phonecode' => '20'),
            array('id' => '64',        'name' => 'El Salvador','code' => 'SLV','numcode' => '222','phonecode' => '503'),
            array('id' => '65',        'name' => 'Equatorial Guinea','code' => 'GNQ','numcode' => '226','phonecode' => '240'),
            array('id' => '66',            'name' => 'Eritrea','code' => 'ERI','numcode' => '232','phonecode' => '291'),
            array('id' => '67',            'name' => 'Estonia','code' => 'EST','numcode' => '233','phonecode' => '372'),
            array('id' => '68',            'name' => 'Ethiopia','code' => 'ETH','numcode' => '231','phonecode' => '251'),
            array('id' => '69',        'name' => 'Falkland Islands (Malvinas)','code' => 'FLK','numcode' => '238','phonecode' => '500'),
            array('id' => '70',        'name' => 'Faroe Islands','code' => 'FRO','numcode' => '234','phonecode' => '298'),
            array('id' => '71',            'name' => 'Fiji','code' => 'FJI','numcode' => '242','phonecode' => '679'),
            array('id' => '72',            'name' => 'Finland','code' => 'FIN','numcode' => '246','phonecode' => '358'),
            array('id' => '73',        'name' => 'France','code' => 'FRA','numcode' => '250','phonecode' => '33'),
            array('id' => '74',        'name' => 'French Guiana','code' => 'GUF','numcode' => '254','phonecode' => '594'),
            array('id' => '75',        'name' => 'French Polynesia','code' => 'PYF','numcode' => '258','phonecode' => '689'),
            array('id' => '76',        'name' => 'French Southern Territories','code' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '77',        'name' => 'Gabon','code' => 'GAB','numcode' => '266','phonecode' => '241'),
            array('id' => '78',        'name' => 'Gambia','code' => 'GMB','numcode' => '270','phonecode' => '220'),
            array('id' => '79',            'name' => 'Georgia','code' => 'GEO','numcode' => '268','phonecode' => '995'),
            array('id' => '80',            'name' => 'Germany','code' => 'DEU','numcode' => '276','phonecode' => '49'),
            array('id' => '81',        'name' => 'Ghana','code' => 'GHA','numcode' => '288','phonecode' => '233'),
            array('id' => '82',        'name' => 'Gibraltar','code' => 'GIB','numcode' => '292','phonecode' => '350'),
            array('id' => '83',        'name' => 'Greece','code' => 'GRC','numcode' => '300','phonecode' => '30'),
            array('id' => '84',        'name' => 'Greenland','code' => 'GRL','numcode' => '304','phonecode' => '299'),
            array('id' => '85',            'name' => 'Grenada','code' => 'GRD','numcode' => '308','phonecode' => '1473'),
            array('id' => '86',        'name' => 'Guadeloupe','code' => 'GLP','numcode' => '312','phonecode' => '590'),
            array('id' => '87',            'name' => 'Guam','code' => 'GUM','numcode' => '316','phonecode' => '1671'),
            array('id' => '88',        'name' => 'Guatemala','code' => 'GTM','numcode' => '320','phonecode' => '502'),
            array('id' => '89',        'name' => 'Guinea','code' => 'GIN','numcode' => '324','phonecode' => '224'),
            array('id' => '90',        'name' => 'Guinea-Bissau','code' => 'GNB','numcode' => '624','phonecode' => '245'),
            array('id' => '91',        'name' => 'Guyana','code' => 'GUY','numcode' => '328','phonecode' => '592'),
            array('id' => '92',        'name' => 'Haiti','code' => 'HTI','numcode' => '332','phonecode' => '509'),
            array('id' => '93',        'name' => 'Heard Island and Mcdonald Islands','code' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '94',    'name' => 'Holy See (Vatican City State)','code' => 'VAT','numcode' => '336','phonecode' => '39'),
            array('id' => '95',            'name' => 'Honduras','code' => 'HND','numcode' => '340','phonecode' => '504'),
            array('id' => '96',        'name' => 'Hong Kong','code' => 'HKG','numcode' => '344','phonecode' => '852'),
            array('id' => '97',            'name' => 'Hungary','code' => 'HUN','numcode' => '348','phonecode' => '36'),
            array('id' => '98',            'name' => 'Iceland','code' => 'ISL','numcode' => '352','phonecode' => '354'),
            array('id' => '99',        'name' => 'India','code' => 'IND','numcode' => '356','phonecode' => '91'),
            array('id' => '100',       'name' => 'Indonesia','code' => 'IDN','numcode' => '360','phonecode' => '62'),
            array('id' => '101',       'name' => 'Iran, Islamic Republic of','code' => 'IRN','numcode' => '364','phonecode' => '98'),
            array('id' => '102',           'name' => 'Iraq','code' => 'IRQ','numcode' => '368','phonecode' => '964'),
            array('id' => '103',           'name' => 'Ireland','code' => 'IRL','numcode' => '372','phonecode' => '353'),
            array('id' => '104',       'name' => 'Israel','code' => 'ISR','numcode' => '376','phonecode' => '972'),
            array('id' => '105',       'name' => 'Italy','code' => 'ITA','numcode' => '380','phonecode' => '39'),
            array('id' => '106',           'name' => 'Jamaica','code' => 'JAM','numcode' => '388','phonecode' => '1876'),
            array('id' => '107',       'name' => 'Japan','code' => 'JPN','numcode' => '392','phonecode' => '81'),
            array('id' => '108',       'name' => 'Jordan','code' => 'JOR','numcode' => '400','phonecode' => '962'),
            array('id' => '109',       'name' => 'Kazakhstan','code' => 'KAZ','numcode' => '398','phonecode' => '7'),
            array('id' => '110',       'name' => 'Kenya','code' => 'KEN','numcode' => '404','phonecode' => '254'),
            array('id' => '111',           'name' => 'Kiribati','code' => 'KIR','numcode' => '296','phonecode' => '686'),
            array('id' => '112',       'name' => 'Korea, Democratic People\'s Republic of','code' => 'PRK','numcode' => '408','phonecode' => '850'),
            array('id' => '113',   'name' => 'Korea, Republic of','code' => 'KOR','numcode' => '410','phonecode' => '82'),
            array('id' => '114',       'name' => 'Kuwait','code' => 'KWT','numcode' => '414','phonecode' => '965'),
            array('id' => '115',       'name' => 'Kyrgyzstan','code' => 'KGZ','numcode' => '417','phonecode' => '996'),
            array('id' => '116',       'name' => 'Lao People\'s Democratic Republic','code' => 'LAO','numcode' => '418','phonecode' => '856'),
            array('id' => '117',       'name' => 'Latvia','code' => 'LVA','numcode' => '428','phonecode' => '371'),
            array('id' => '118',           'name' => 'Lebanon','code' => 'LBN','numcode' => '422','phonecode' => '961'),
            array('id' => '119',           'name' => 'Lesotho','code' => 'LSO','numcode' => '426','phonecode' => '266'),
            array('id' => '120',           'name' => 'Liberia','code' => 'LBR','numcode' => '430','phonecode' => '231'),
            array('id' => '121',       'name' => 'Libyan Arab Jamahiriya','code' => 'LBY','numcode' => '434','phonecode' => '218'),
            array('id' => '122',       'name' => 'Liechtenstein','code' => 'LIE','numcode' => '438','phonecode' => '423'),
            array('id' => '123',       'name' => 'Lithuania','code' => 'LTU','numcode' => '440','phonecode' => '370'),
            array('id' => '124',       'name' => 'Luxembourg','code' => 'LUX','numcode' => '442','phonecode' => '352'),
            array('id' => '125',       'name' => 'Macao','code' => 'MAC','numcode' => '446','phonecode' => '853'),
            array('id' => '126',       'name' => 'Macedonia, the Former Yugoslav Republic of','code' => 'MKD','numcode' => '807','phonecode' => '389'),
            array('id' => '127',       'name' => 'Madagascar','code' => 'MDG','numcode' => '450','phonecode' => '261'),
            array('id' => '128',       'name' => 'Malawi','code' => 'MWI','numcode' => '454','phonecode' => '265'),
            array('id' => '129',           'name' => 'Malaysia','code' => 'MYS','numcode' => '458','phonecode' => '60'),
            array('id' => '130',           'name' => 'Maldives','code' => 'MDV','numcode' => '462','phonecode' => '960'),
            array('id' => '131',           'name' => 'Mali','code' => 'MLI','numcode' => '466','phonecode' => '223'),
            array('id' => '132',       'name' => 'Malta','code' => 'MLT','numcode' => '470','phonecode' => '356'),
            array('id' => '133',       'name' => 'Marshall Islands','code' => 'MHL','numcode' => '584','phonecode' => '692'),
            array('id' => '134',       'name' => 'Martinique','code' => 'MTQ','numcode' => '474','phonecode' => '596'),
            array('id' => '135',       'name' => 'Mauritania','code' => 'MRT','numcode' => '478','phonecode' => '222'),
            array('id' => '136',       'name' => 'Mauritius','code' => 'MUS','numcode' => '480','phonecode' => '230'),
            array('id' => '137',           'name' => 'Mayotte','code' => NULL,'numcode' => NULL,'phonecode' => '269'),
            array('id' => '138',       'name' => 'Mexico','code' => 'MEX','numcode' => '484','phonecode' => '52'),
            array('id' => '139',       'name' => 'Micronesia, Federated States of','code' => 'FSM','numcode' => '583','phonecode' => '691'),
            array('id' => '140',       'name' => 'Moldova, Republic of','code' => 'MDA','numcode' => '498','phonecode' => '373'),
            array('id' => '141',       'name' => 'Monaco','code' => 'MCO','numcode' => '492','phonecode' => '377'),
            array('id' => '142',           'name' => 'Mongolia','code' => 'MNG','numcode' => '496','phonecode' => '976'),
            array('id' => '143',       'name' => 'Montserrat','code' => 'MSR','numcode' => '500','phonecode' => '1664'),
            array('id' => '144',           'name' => 'Morocco','code' => 'MAR','numcode' => '504','phonecode' => '212'),
            array('id' => '145',       'name' => 'Mozambique','code' => 'MOZ','numcode' => '508','phonecode' => '258'),
            array('id' => '146',           'name' => 'Myanmar','code' => 'MMR','numcode' => '104','phonecode' => '95'),
            array('id' => '147',           'name' => 'Namibia','code' => 'NAM','numcode' => '516','phonecode' => '264'),
            array('id' => '148',       'name' => 'Nauru','code' => 'NRU','numcode' => '520','phonecode' => '674'),
            array('id' => '149',       'name' => 'Nepal','code' => 'NPL','numcode' => '524','phonecode' => '977'),
            array('id' => '150',           'name' => 'Netherlands','code' => 'NLD','numcode' => '528','phonecode' => '31'),
            array('id' => '151',       'name' => 'Netherlands Antilles','code' => 'ANT','numcode' => '530','phonecode' => '599'),
            array('id' => '152',       'name' => 'New Caledonia','code' => 'NCL','numcode' => '540','phonecode' => '687'),
            array('id' => '153',       'name' => 'New Zealand','code' => 'NZL','numcode' => '554','phonecode' => '64'),
            array('id' => '154',       'name' => 'Nicaragua','code' => 'NIC','numcode' => '558','phonecode' => '505'),
            array('id' => '155',       'name' => 'Niger','code' => 'NER','numcode' => '562','phonecode' => '227'),
            array('id' => '156',           'name' => 'Nigeria','code' => 'NGA','numcode' => '566','phonecode' => '234'),
            array('id' => '157',           'name' => 'Niue','code' => 'NIU','numcode' => '570','phonecode' => '683'),
            array('id' => '158',   'name' => 'Norfolk Island','code' => 'NFK','numcode' => '574','phonecode' => '672'),
            array('id' => '159',   'name' => 'Northern Mariana Islands','code' => 'MNP','numcode' => '580','phonecode' => '1670'),
            array('id' => '160',       'name' => 'Norway','code' => 'NOR','numcode' => '578','phonecode' => '47'),
            array('id' => '161',           'name' => 'Oman','code' => 'OMN','numcode' => '512','phonecode' => '968'),
            array('id' => '162',           'name' => 'Pakistan','code' => 'PAK','numcode' => '586','phonecode' => '92'),
            array('id' => '163',       'name' => 'Palau','code' => 'PLW','numcode' => '585','phonecode' => '680'),
            array('id' => '164',       'name' => 'Palestinian Territory, Occupied','code' => NULL,'numcode' => NULL,'phonecode' => '970'),
            array('id' => '165',       'name' => 'Panama','code' => 'PAN','numcode' => '591','phonecode' => '507'),
            array('id' => '166',       'name' => 'Papua New Guinea','code' => 'PNG','numcode' => '598','phonecode' => '675'),
            array('id' => '167',           'name' => 'Paraguay','code' => 'PRY','numcode' => '600','phonecode' => '595'),
            array('id' => '168',           'name' => 'Peru','code' => 'PER','numcode' => '604','phonecode' => '51'),
            array('id' => '169',           'name' => 'Philippines','code' => 'PHL','numcode' => '608','phonecode' => '63'),
            array('id' => '170',           'name' => 'Pitcairn','code' => 'PCN','numcode' => '612','phonecode' => '0'),
            array('id' => '171',       'name' => 'Poland','code' => 'POL','numcode' => '616','phonecode' => '48'),
            array('id' => '172',           'name' => 'Portugal','code' => 'PRT','numcode' => '620','phonecode' => '351'),
            array('id' => '173',       'name' => 'Puerto Rico','code' => 'PRI','numcode' => '630','phonecode' => '1787'),
            array('id' => '174',       'name' => 'Qatar','code' => 'QAT','numcode' => '634','phonecode' => '974'),
            array('id' => '175',           'name' => 'Reunion','code' => 'REU','numcode' => '638','phonecode' => '262'),
            array('id' => '176',           'name' => 'Romania','code' => 'ROM','numcode' => '642','phonecode' => '40'),
            array('id' => '177',   'name' => 'Russian Federation','code' => 'RUS','numcode' => '643','phonecode' => '70'),
            array('id' => '178',       'name' => 'Rwanda','code' => 'RWA','numcode' => '646','phonecode' => '250'),
            array('id' => '179',       'name' => 'Saint Helena','code' => 'SHN','numcode' => '654','phonecode' => '290'),
            array('id' => '180',       'name' => 'Saint Kitts and Nevis','code' => 'KNA','numcode' => '659','phonecode' => '1869'),
            array('id' => '181',       'name' => 'Saint Lucia','code' => 'LCA','numcode' => '662','phonecode' => '1758'),
            array('id' => '182',   'name' => 'Saint Pierre and Miquelon','code' => 'SPM','numcode' => '666','phonecode' => '508'),
            array('id' => '183',   'name' => 'Saint Vincent and the Grenadines','code' => 'VCT','numcode' => '670','phonecode' => '1784'),
            array('id' => '184',       'name' => 'Samoa','code' => 'WSM','numcode' => '882','phonecode' => '684'),
            array('id' => '185',   'name' => 'San Marino','code' => 'SMR','numcode' => '674','phonecode' => '378'),
            array('id' => '186',       'name' => 'Sao Tome and Principe','code' => 'STP','numcode' => '678','phonecode' => '239'),
            array('id' => '187',       'name' => 'Saudi Arabia','code' => 'SAU','numcode' => '682','phonecode' => '966'),
            array('id' => '188',           'name' => 'Senegal','code' => 'SEN','numcode' => '686','phonecode' => '221'),
            array('id' => '189',   'name' => 'Serbia and Montenegro','code' => NULL,'numcode' => NULL,'phonecode' => '381'),
            array('id' => '190',       'name' => 'Seychelles','code' => 'SYC','numcode' => '690','phonecode' => '248'),
            array('id' => '191',       'name' => 'Sierra Leone','code' => 'SLE','numcode' => '694','phonecode' => '232'),
            array('id' => '192',       'name' => 'Singapore','code' => 'SGP','numcode' => '702','phonecode' => '65'),
            array('id' => '193',           'name' => 'Slovakia','code' => 'SVK','numcode' => '703','phonecode' => '421'),
            array('id' => '194',           'name' => 'Slovenia','code' => 'SVN','numcode' => '705','phonecode' => '386'),
            array('id' => '195',       'name' => 'Solomon Islands','code' => 'SLB','numcode' => '90','phonecode' => '677'),
            array('id' => '196',           'name' => 'Somalia','code' => 'SOM','numcode' => '706','phonecode' => '252'),
            array('id' => '197',       'name' => 'South Africa','code' => 'ZAF','numcode' => '710','phonecode' => '27'),
            array('id' => '198',       'name' => 'South Georgia and the South Sandwich Islands','code' => NULL,'numcode' => NULL,'phonecode' => '0'),
            array('id' => '199',       'name' => 'Spain','code' => 'ESP','numcode' => '724','phonecode' => '34'),
            array('id' => '200',       'name' => 'Sri Lanka','code' => 'LKA','numcode' => '144','phonecode' => '94'),
            array('id' => '201',       'name' => 'Sudan','code' => 'SDN','numcode' => '736','phonecode' => '249'),
            array('id' => '202',           'name' => 'Suriname','code' => 'SUR','numcode' => '740','phonecode' => '597'),
            array('id' => '203',       'name' => 'Svalbard and Jan Mayen','code' => 'SJM','numcode' => '744','phonecode' => '47'),
            array('id' => '204',       'name' => 'Swaziland','code' => 'SWZ','numcode' => '748','phonecode' => '268'),
            array('id' => '205',       'name' => 'Sweden','code' => 'SWE','numcode' => '752','phonecode' => '46'),
            array('id' => '206',           'name' => 'Switzerland','code' => 'CHE','numcode' => '756','phonecode' => '41'),
            array('id' => '207',       'name' => 'Syrian Arab Republic','code' => 'SYR','numcode' => '760','phonecode' => '963'),
            array('id' => '208',       'name' => 'Taiwan, Province of China','code' => 'TWN','numcode' => '158','phonecode' => '886'),
            array('id' => '209',       'name' => 'Tajikistan','code' => 'TJK','numcode' => '762','phonecode' => '992'),
            array('id' => '210',       'name' => 'Tanzania, United Republic of','code' => 'TZA','numcode' => '834','phonecode' => '255'),
            array('id' => '211',           'name' => 'Thailand','code' => 'THA','numcode' => '764','phonecode' => '66'),
            array('id' => '212',       'name' => 'Timor-Leste','code' => NULL,'numcode' => NULL,'phonecode' => '670'),
            array('id' => '213',           'name' => 'Togo','code' => 'TGO','numcode' => '768','phonecode' => '228'),
            array('id' => '214',           'name' => 'Tokelau','code' => 'TKL','numcode' => '772','phonecode' => '690'),
            array('id' => '215',       'name' => 'Tonga','code' => 'TON','numcode' => '776','phonecode' => '676'),
            array('id' => '216',       'name' => 'Trinidad and Tobago','code' => 'TTO','numcode' => '780','phonecode' => '1868'),
            array('id' => '217',           'name' => 'Tunisia','code' => 'TUN','numcode' => '788','phonecode' => '216'),
            array('id' => '218',       'name' => 'Turkey','code' => 'TUR','numcode' => '792','phonecode' => '90'),
            array('id' => '219',           'name' => 'Turkmenistan','code' => 'TKM','numcode' => '795','phonecode' => '7370'),
            array('id' => '220',       'name' => 'Turks and Caicos Islands','code' => 'TCA','numcode' => '796','phonecode' => '1649'),
            array('id' => '221',       'name' => 'Tuvalu','code' => 'TUV','numcode' => '798','phonecode' => '688'),
            array('id' => '222',       'name' => 'Uganda','code' => 'UGA','numcode' => '800','phonecode' => '256'),
            array('id' => '223',           'name' => 'Ukraine','code' => 'UKR','numcode' => '804','phonecode' => '380'),
            array('id' => '224',       'name' => 'United Arab Emirates','code' => 'ARE','numcode' => '784','phonecode' => '971'),
            array('id' => '225',   'name' => 'United Kingdom','code' => 'GBR','numcode' => '826','phonecode' => '44'),
            array('id' => '226',       'name' => 'United States','code' => 'USA','numcode' => '840','phonecode' => '1'),
            array('id' => '227',       'name' => 'United States Minor Outlying Islands','code' => NULL,'numcode' => NULL,'phonecode' => '1'),
            array('id' => '228',           'name' => 'Uruguay','code' => 'URY','numcode' => '858','phonecode' => '598'),
            array('id' => '229',       'name' => 'Uzbekistan','code' => 'UZB','numcode' => '860','phonecode' => '998'),
            array('id' => '230',           'name' => 'Vanuatu','code' => 'VUT','numcode' => '548','phonecode' => '678'),
            array('id' => '231',       'name' => 'Venezuela','code' => 'VEN','numcode' => '862','phonecode' => '58'),
            array('id' => '232',       'name' => 'Viet Nam','code' => 'VNM','numcode' => '704','phonecode' => '84'),
            array('id' => '233',       'name' => 'Virgin Islands, British','code' => 'VGB','numcode' => '92','phonecode' => '1284'),
            array('id' => '234',       'name' => 'Virgin Islands, U.s.','code' => 'VIR','numcode' => '850','phonecode' => '1340'),
            array('id' => '235',       'name' => 'Wallis and Futuna','code' => 'WLF','numcode' => '876','phonecode' => '681'),
            array('id' => '236',   'name' => 'Western Sahara','code' => 'ESH','numcode' => '732','phonecode' => '212'),
            array('id' => '237',       'name' => 'Yemen','code' => 'YEM','numcode' => '887','phonecode' => '967'),
            array('id' => '238',       'name' => 'Zambia','code' => 'ZMB','numcode' => '894','phonecode' => '260'),
            array('id' => '239',           'name' => 'Zimbabwe','code' => 'ZWE','numcode' => '716','phonecode' => '263'),
            array('id' => '240',       'name' => 'Serbia','code' => 'SRB','numcode' => '688','phonecode' => '381'),
            array('id' => '241',           'name' => 'Asia / Pacific Region','code' => '0','numcode' => '0','phonecode' => '0'),
            array('id' => '242',       'name' => 'Montenegro','code' => 'MNE','numcode' => '499','phonecode' => '382'),
            array('id' => '243',       'name' => 'Aland Islands','code' => 'ALA','numcode' => '248','phonecode' => '358'),
            array('id' => '244',       'name' => 'Bonaire, Sint Eustatius and Saba','code' => 'BES','numcode' => '535','phonecode' => '599'),
            array('id' => '245',           'name' => 'Curacao','code' => 'CUW','numcode' => '531','phonecode' => '599'),
            array('id' => '246',           'name' => 'Guernsey','code' => 'GGY','numcode' => '831','phonecode' => '44'),
            array('id' => '247',   'name' => 'Isle of Man','code' => 'IMN','numcode' => '833','phonecode' => '44'),
            array('id' => '248',   'name' => 'Jersey','code' => 'JEY','numcode' => '832','phonecode' => '44'),
            array('id' => '249',   'name' => 'Kosovo','code' => '---','numcode' => '0','phonecode' => '381'),
            array('id' => '250',   'name' => 'Saint Barthelemy','code' => 'BLM','numcode' => '652','phonecode' => '590'),
            array('id' => '251',   'name' => 'Saint Martin','code' => 'MAF','numcode' => '663','phonecode' => '590'),
            array('id' => '252',   'name' => 'Sint Maarten','code' => 'SXM','numcode' => '534','phonecode' => '1'),
            array('id' => '253',   'name' => 'South Sudan','code' => 'SSD','numcode' => '728','phonecode' => '211')
          );
          foreach ($aCountries as $country) {
            Country::create($country);
          }
    }
}
