# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.2


pipelines:
  default:
     - step:
        name: 'Build and Test'
        script:
           - echo 'Everything is awesome!'
           - apt-get update
           - apt-get install -y zip
           - zip -r HOS_ClinicALL-$BITBUCKET_BUILD_NUMBER.zip .
           - pipe: atlassian/aws-elasticbeanstalk-deploy:0.6.6
             variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_STAGING
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_STAGING
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_STAGING
              APPLICATION_NAME: $APPLICATION_NAME_STAGING
              S3_BUCKET: $S3_BUCKET_STAGING
              COMMAND: 'upload-only'
              ZIP_FILE: 'HOS_ClinicALL-$BITBUCKET_BUILD_NUMBER.zip'
              
              VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-multiple'